name: Publish

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Build core
        run: yarn workspace @excalidraw-to-mermaid/core build

      - name: Build CLI
        run: yarn workspace @excalidraw-to-mermaid/cli build

      - name: Publish core 🚀
        run: yarn workspace @excalidraw-to-mermaid/core publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish CLI 🚀
        run: yarn workspace @excalidraw-to-mermaid/cli publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
